name: CI

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build for common architectures
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && github.event.ref == 'refs/heads/main')
      &&
      !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    strategy:
      matrix:
        thread: [ 0, 1, 2 ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@c0916f0a41f13444612a8f0f5e700ea34edd7c19 # v0.5.3
      - uses: ./.github/promci/actions/build
        with:
          promu_opts: "-p linux/amd64 -p windows/amd64 -p darwin/amd64 -p linux/arm64 -p windows/arm64 -p darwin/arm64"
          parallelism: 3
          thread: ${{ matrix.thread }}

  build_all:
    name: Build for all architectures
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
      ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    strategy:
      matrix:
        thread: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@c0916f0a41f13444612a8f0f5e700ea34edd7c19 # v0.5.3
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 12
          thread: ${{ matrix.thread }}

  verify-example-configs:
    name: Verify
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.25-base
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: make build
      - name: Verify example configs
        run: find ./examples -name "*.yml" -print0 | xargs -0 -I % ./yace verify-config -config.file %

  publish_main:
    name: Publish main branch artifacts
    runs-on: ubuntu-latest
    needs: [build_all, verify-example-configs]
    if: |
      (github.repository == 'prometheus-community/fortigate_exporter')
      &&
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@c0916f0a41f13444612a8f0f5e700ea34edd7c19 # v0.5.3
      - uses: ./.github/promci/actions/publish_main
        with:
          docker_hub_organization: prometheuscommunity
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_organization: prometheuscommunity
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}

  publish_release:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    needs: [build_all, verify-example-configs]
    if: |
      (github.repository == 'prometheus-community/fortigate_exporter')
      &&
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prometheus/promci@c0916f0a41f13444612a8f0f5e700ea34edd7c19 # v0.5.3
      - uses: ./.github/promci/actions/publish_release
        with:
          docker_hub_organization: prometheuscommunity
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_organization: prometheuscommunity
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
          github_token: ${{ secrets.PROMBOT_GITHUB_TOKEN }}
